# Config file for Gas_Price_Scraper

#### CHange file name to .config.yml before use
#### Place file in user home directory in order to use.

general:
  GasPriceURL: "https://gasprices.aaa.com/?state=CA#state-metro"
  output: "mysql"
  #output: "csv"
csv:
  filepath: "/path/to/output/file.csv"
mysql:
  host: 1.1.1.1
  port: 3306
  user: "abc"
  password: "123"
  database: "ev_tracking"
logging:
  filepath: "/path/to/log/file.log"
